# Generated by Django 3.0.2 on 2020-02-13 16:47

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AzureCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Category name')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='AzureTechnology',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Category name')),
                ('azureCategory', models.ForeignKey(default=0, null=True, on_delete=django.db.models.deletion.CASCADE, to='csa.AzureCategory')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='CSAuser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30, verbose_name='First Name')),
                ('last_name', models.CharField(max_length=30, verbose_name='Last name')),
                ('alias', models.CharField(max_length=30, verbose_name='Alias')),
                ('area', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='csa.AzureCategory')),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tpid', models.IntegerField(verbose_name='TPID')),
                ('name', models.CharField(max_length=50, verbose_name='Customer name')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='workRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alias', models.CharField(max_length=50, verbose_name='Your alias')),
                ('creationDate', models.DateField(default=django.utils.timezone.now)),
                ('job_title', models.CharField(choices=[('ae', 'AE'), ('ats', 'ATS'), ('tam', 'TAM'), ('specialist', 'Specialist'), ('dir', 'Dir sales')], default='', max_length=50)),
                ('engagement', models.CharField(default='', max_length=10)),
                ('customer_area', models.CharField(choices=[('rh', 'Recursos humanos'), ('ti', 'TI'), ('finanzas', 'Finanzas'), ('merca', 'Mercadotecnia'), ('seguridad', 'Seguridad')], default='ti', max_length=50)),
                ('request_title', models.CharField(default='', max_length=100)),
                ('request_desc', models.CharField(default='', max_length=200)),
                ('request_date', models.DateField(default=django.utils.timezone.now, verbose_name='Expected Start Date')),
                ('request_status', models.CharField(choices=[('unknown', 'Unknown'), ('inprogress', 'In progress'), ('hold', 'On Hold'), ('finished', 'Finished')], default='unknown', max_length=50)),
                ('assigned_csa', models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.CASCADE, to='csa.CSAuser')),
                ('customer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='csa.Customer')),
                ('request_category', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='csa.AzureCategory')),
                ('request_tech', models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.CASCADE, to='csa.AzureTechnology')),
            ],
        ),
    ]
