# Generated by Django 2.1.11 on 2019-09-13 00:00

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('csa', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='workrequest',
            old_name='alias_requester',
            new_name='alias',
        ),
        migrations.RemoveField(
            model_name='workrequest',
            name='instrument',
        ),
        migrations.RemoveField(
            model_name='workrequest',
            name='last_name',
        ),
        migrations.AddField(
            model_name='workrequest',
            name='creationDate',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='workrequest',
            name='customer',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='workrequest',
            name='customer_area',
            field=models.CharField(choices=[('rh', 'Recursos humanos'), ('ti', 'TI'), ('finanzas', 'Finanzas'), ('merca', 'Mercadotecnia'), ('seguridad', 'Seguridad')], default='ti', max_length=50),
        ),
        migrations.AddField(
            model_name='workrequest',
            name='engagementID',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AddField(
            model_name='workrequest',
            name='job_title',
            field=models.CharField(choices=[('ae', 'AE'), ('ats', 'ATS'), ('tam', 'TAM'), ('specialist', 'Specialist'), ('dir', 'Dir sales')], default='', max_length=50),
        ),
        migrations.AddField(
            model_name='workrequest',
            name='request_category',
            field=models.CharField(choices=[('appsinfra', 'APPS & INFRA'), ('dataai', 'DATA & AI')], default='', max_length=50),
        ),
        migrations.AddField(
            model_name='workrequest',
            name='request_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='workrequest',
            name='request_desc',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='workrequest',
            name='request_tech',
            field=models.CharField(choices=[('aks', 'AKS'), ('bi', 'bBI'), ('bigdata', 'Big data (Databricks, HDI)'), ('devops', 'DevOps'), ('dwh', 'Data warehouse'), ('iot', 'IoT'), ('oss', 'Open Source'), ('sql', 'Migración SQL')], default='', max_length=50),
        ),
        migrations.AddField(
            model_name='workrequest',
            name='request_title',
            field=models.CharField(default='', max_length=100),
        ),
    ]
