# Generated by Django 2.1.11 on 2019-09-13 00:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('csa', '0002_auto_20190912_1900'),
    ]

    operations = [
        migrations.RenameField(
            model_name='workrequest',
            old_name='engagementID',
            new_name='engagement',
        ),
    ]
