# Generated by Django 3.0.2 on 2020-02-13 16:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('csa', '0002_workrequest2'),
    ]

    operations = [
        migrations.DeleteModel(
            name='workRequest2',
        ),
    ]
