# Generated by Django 2.1.11 on 2019-09-13 21:21

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('csa', '0003_auto_20190912_1928'),
    ]

    operations = [
        migrations.CreateModel(
            name='CSAuser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30, verbose_name='First Name')),
                ('last_name', models.CharField(max_length=30, verbose_name='Last name')),
                ('alias', models.CharField(max_length=30, verbose_name='Alias')),
            ],
        ),
        migrations.AlterField(
            model_name='workrequest',
            name='alias',
            field=models.CharField(max_length=50, verbose_name='Your alias'),
        ),
        migrations.AlterField(
            model_name='workrequest',
            name='request_date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Expected Start Date'),
        ),
        migrations.AddField(
            model_name='workrequest',
            name='assigned_csa',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='csa.CSAuser'),
        ),
    ]
