# Generated by Django 3.0.2 on 2020-02-13 16:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('csa', '0003_delete_workrequest2'),
    ]

    operations = [
        migrations.CreateModel(
            name='CSAuser2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30, verbose_name='First Name')),
                ('last_name', models.CharField(max_length=30, verbose_name='Last name')),
                ('alias', models.CharField(max_length=30, verbose_name='Alias')),
                ('area', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='csa.AzureCategory')),
            ],
        ),
    ]
