# Generated by Django 3.0.2 on 2020-02-13 16:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('csa', '0004_csauser2'),
    ]

    operations = [
        migrations.RenameField(
            model_name='csauser',
            old_name='area',
            new_name='area_id',
        ),
        migrations.DeleteModel(
            name='CSAuser2',
        ),
    ]
