# Generated by Django 2.1.11 on 2019-09-17 18:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('csa', '0005_auto_20190913_1622'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workrequest',
            name='assigned_csa',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.CASCADE, to='csa.CSAuser'),
        ),
    ]
