# Generated by Django 3.0.2 on 2020-02-13 18:20

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('csa', '0008_auto_20200213_1103'),
    ]

    operations = [
        migrations.CreateModel(
            name='workRequestUpdate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modificationDate', models.DateField(default=django.utils.timezone.now)),
                ('notification_status', models.IntegerField(verbose_name='notification_status')),
                ('csa', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='csa.CSAuser')),
                ('workRequest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='csa.workRequest')),
            ],
        ),
    ]
