# Generated by Django 3.0.2 on 2020-02-13 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('csa', '0009_workrequestupdate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workrequestupdate',
            name='notification_status',
            field=models.IntegerField(default=0, verbose_name='notification_status'),
        ),
    ]
