# Generated by Django 3.0.2 on 2020-02-13 18:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('csa', '0010_auto_20200213_1222'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workrequest',
            name='assigned_csa',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='csa.CSAuser'),
        ),
    ]
